#!/bin/bash
set -f

exec < /dev/tty 3>&1 > /dev/tty

printf %s "push <attach-file>" >&3

read -p "Attempt to attach from the clipboard? (y/n)" -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then

    tempfile="`dirname ~/.mail/temporary/attached`/attached".$(date +"%m.%d.%y.%H.%M.%S")
    clipboard=`pbpaste`
    if [[ $clipboard == http* ]]
    then
        suffix=`echo "$clipboard" | awk -F . '{print $NF}'`
        tempfile="$tempfile.$suffix"
        curl "$clipboard" -o $tempfile
    else
        suffix="png"
        tempfile="$tempfile.$suffix"
        pngpaste "$tempfile" || tempfile="empty"
    fi

    printf %s $tempfile >&3
    printf %s "<enter>" >&3
fi
