#!/bin/bash
set -f

exec < /dev/tty 3>&1 > /dev/tty

printf %s "push <attach-file>" >&3

_fill () {
    printf $1 >&3
    printf %s "<enter>" >&3
}

read -p "Attempt to attach from the clipboard? (y/n)" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then

    tempfile="`dirname ~/.mail/temporary/attached`/attached".$(date +"%m.%d.%y.%H.%M.%S")
    clipboard=`pbpaste`
    if [[ $clipboard == http* ]]
    then
        curl -L $(printf '%q' $clipboard) -o $tempfile
    else
        clipboard="`osascript -e 'POSIX path of (the clipboard as «class furl»)'`"
        if [[ $? != 0 ]]
        then
            tempfile="$tempfile.png"
            (pngpaste "$tempfile" && _fill $tempfile) || _fill "(empty)"
            exit 0
        fi
        cp "$clipboard" $tempfile
    fi

    mimetype=$(file --mime-type -b "$tempfile")
    suffix=$(python -c "import mimetypes; print mimetypes.guess_extension('$mimetype').replace('.ksh', '.txt')")
    mv $tempfile "$tempfile$suffix"
    tempfile="$tempfile$suffix"

    _fill $tempfile
fi
printf "\ec"  # don't trash the screen with download history
