#!/bin/bash

doalarm () { perl -e 'alarm shift; exec @ARGV' "$@"; } # define a helper function

while true; do
  echo "waiting for IDLE"
  doalarm 30 python ~/.mutt/idle.py
  echo "downloading new mail"
  doalarm 120 /usr/local/bin/mbsync --all & pid1=$!
  wait $pid1
  /usr/local/bin/notmuch new
done
