#!/bin/bash

doalarm () { perl -e 'alarm shift; exec @ARGV' "$@"; } # define a helper function

while true; do
  echo "waiting for IDLE"
  doalarm 30 python2 ~/.mutt/idle.py

  # redraw all tmux clients so they show a 'mail downloading' icon in the status bar
  /bin/bash -c 'sleep 2; for c in $(/usr/local/bin/tmux list-clients | cut -d" " -f1 | cut -d":" -f1); do /usr/local/bin/tmux refresh-client -S -t "$c"; done;' &

  /usr/local/bin/notmuch tag -new -- tag:new

  echo "downloading new mail"
  doalarm 120 /usr/local/bin/offlineimap -a Ryan & pid1=$!
  doalarm 120 /usr/local/bin/offlineimap -a RH & pid2=$!
  wait $pid1
  /usr/local/bin/notmuch new
  /usr/local/bin/notmuch tag -new -- tag:new
  wait $pid2
  /usr/local/bin/notmuch new
  /usr/local/bin/notmuch tag -new -- tag:new

  # redraw all tmux clients so the 'mail downloading' icon disappears
  /bin/bash -c 'sleep 2; for c in $(/usr/local/bin/tmux list-clients | cut -d" " -f1 | cut -d":" -f1); do /usr/local/bin/tmux refresh-client -S -t "$c"; done;' &
done
