#! /bin/sh

# pip install watchdog
# brew install terminal-notifier

MESSAGE=`python -c "
import email
import hashlib
import os
import sys

if not os.path.isfile('$1'):
    sys.exit(1)
with open('$1') as mail_file:
    msg = email.message_from_file(mail_file)
    name, address = email.utils.parseaddr(msg['From'])
    url = 'http://www.gravatar.com/avatar/%s?d=mm' % hashlib.md5(address).hexdigest()
    print '\n'.join([name, msg['Subject'], url])
"` || exit 1

FOLDER=$(echo $(dirname $(dirname $1)) | sed "s/.mail\//=/")

PHOTO=`echo "$MESSAGE" | tail -n1`
MESSAGE=`echo "$MESSAGE" | head -n2`

terminal-notifier -message "$MESSAGE" -title "Mutt - New Message" -appIcon "$PHOTO" -execute "osascript /Users/ryan/.mutt/open \"$FOLDER\" \"$1\""
