#!/bin/bash

echo "EMAIL	NAME"
notmuch show --entire-thread=false date:1Y..today AND NOT subject:openstack AND from:"$1*" 2>/dev/null | pcregrep -o1 -i "From: (.*$1[^>]*>)" 2>/dev/null | grep -v -E "(github|twitter|linkedin|openstack|plus.google|launchpad|pinterest|paperlesspost|zendesk|gerrit|beanstalkapp|tenderapp|jira)" | sort | uniq -c | sort -r | tr -s ' ' | cut -d' ' -f3- | tr -d '"' | sed -E 's/([^<]+) <([^>]+)>/\2	\1/' | head -5
