---
database_file: /Users/ryan/.timetrap.db
round_in_seconds: 900
append_notes_delimiter: ' '
formatter_search_paths:
- /Users/ryan/.timetrap/formatters
default_formatter: datesheet
auto_sheet: dotfiles
auto_sheet_search_paths:
- /Users/ryan/.timetrap/auto_sheets
default_command:
auto_checkout: false
require_note: false
