"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['mutt-system-handler.py']
OPTIONS = {
    'argv_emulation': False,
    'plist' : {
        'CFBundleDevelopmentRegion' : 'en',
        'NSPrincipalClass' : 'NSApplication',
        'NSAppleScriptEnabled' : 'YES',
        'LSUIElement' : 'YES',
        'CFBundleIdentifier' : 'org.mutt.mail_scheme_handler',
        'CFBundleURLTypes' : [{
                'CFBundleURLName' : 'eMail Message',
                'CFBundleURLSchemes' : ['mailto']
        }]
    }
}

setup(
    app=APP,
    data_files=[],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
